# Generated by Django 2.2.1 on 2019-05-17 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Blog_id',
            new_name='blog_id',
        ),
    ]
